[package]
name = "snapshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display-info = "0.4.2"
glium = "0.29.1"
winit = "0.28.6"
